"use client";

import { useEffect, useState } from "react";
import { ArrowRight, ChevronRight, Clock3, MapPin, Scissors, Sparkles, UserCheck, Zap, type LucideIcon } from "lucide-react";
import { useBranch } from "@/context/BranchContext";
import { getBookingBarbers, getBookingStatus, type BookingBarber } from "@/lib/publicBookingApi";
import { getServiceCatalog, type ServiceCatalogCategory } from "@/lib/serviceCatalogApi";
import BookingModal, { type BarberBookingInfo, type BookingMode } from "@/components/BookingModal";
import BranchPicker from "@/components/BranchPicker";

type Benefit = [string, string, string, LucideIcon];
type BookingStep = [string, string, string];

const copy: { hero: { eyebrow: string; title: React.ReactNode; body: string }; benefits: Benefit[]; steps: BookingStep[] } = {
  hero: { eyebrow: "THE CUT ISSUE — PREMIUM GROOMING", title: <>Precision Starts Here.<br />Your Look, Your Call.</>, body: "Experience refined grooming at CUT Salon — from precision haircuts and beard detailing to complete preparation for your biggest occasions." },
  benefits: [
    ["01", "Precision in Every Detail", "Cuts and grooming tailored to your features, hair and personal style.", Scissors],
    ["02", "Skilled Professionals", "Choose your preferred barber or let us match you with the right specialist.", UserCheck],
    ["03", "A Clearer Queue", "Organized appointments and queue updates with less uncertainty and waiting.", Clock3],
    ["04", "A Complete Experience", "Hair, beard, skincare and finishing services available in one place.", Sparkles],
  ],
  steps: [
    ["01", "Choose Your Service", "Select the services you need or choose a complete package."],
    ["02", "Pick a Time", "View available times by branch and barber."],
    ["03", "Confirm Your Visit", "Review your selection and receive your booking confirmation."],
  ],
};

const fallbackImages = ["/barber-kareem.jpg", "/barber-mohamed.jpg", "/barber-ziad.jpg", "/barber-bassem.jpg"];
const displayBarber = (barber: BookingBarber, index: number): BarberBookingInfo => ({ id: barber.id, name: barber.name, image: barber.photoUrl || fallbackImages[index % fallbackImages.length], role: barber.job || "CUT Salon Barber", location: "CUT Salon · Alexandria" });
const nearestBarber: BarberBookingInfo = { name: "Nearest available barber", image: "/cutsalon.png", role: "First suitable appointment", location: "CUT Salon · Alexandria" };
const money = (value: number) => new Intl.NumberFormat("en-EG", { style: "currency", currency: "EGP", maximumFractionDigits: 0 }).format(value);

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="flex items-center gap-3 text-xs font-bold tracking-[0.28em] text-cut-warm-beige"><span className="h-2 w-2 rounded-full bg-cut-bronze" /><span className="h-px w-10 bg-cut-bronze/70" />{children}</p>; }

export default function EnglishHome() {
  const { branches, isLoadingBranches, branchesError, selectedBranch, selectBranch } = useBranch();
  const [catalog, setCatalog] = useState<ServiceCatalogCategory[]>([]);
  const [barbers, setBarbers] = useState<BookingBarber[]>([]);
  const [status, setStatus] = useState<"loading" | "enabled" | "closed" | "branch">("loading");
  const [selectedBarber, setSelectedBarber] = useState<BarberBookingInfo | null>(null);
  const [bookingMode, setBookingMode] = useState<BookingMode | undefined>();

  useEffect(() => { getServiceCatalog().then(setCatalog).catch(() => setCatalog([])); }, []);
  useEffect(() => {
    if (!selectedBranch?.branchCode) { setStatus(isLoadingBranches ? "loading" : "branch"); return; }
    let cancelled = false;
    setStatus("loading");
    getBookingStatus(selectedBranch.branchCode).then((result) => { if (!cancelled) setStatus(result.bookingEnabled ? "enabled" : "closed"); }).catch(() => { if (!cancelled) setStatus("closed"); });
    return () => { cancelled = true; };
  }, [isLoadingBranches, selectedBranch?.branchCode]);
  useEffect(() => {
    if (status !== "enabled" || !selectedBranch?.branchCode) return;
    getBookingBarbers(selectedBranch.branchCode).then((result) => setBarbers(result.barbers.filter((barber) => barber.isBookableOnline))).catch(() => setBarbers([]));
  }, [status, selectedBranch?.branchCode]);

  const openBooking = (barber: BarberBookingInfo, mode: BookingMode) => { setBookingMode(mode); setSelectedBarber(barber); };
  const services = catalog.flatMap((category) => category.services.map((service) => ({ ...service, category }))).filter((service) => service.isActive && service.nameEn);
  const featuredServices = catalog.filter((category) => category.services.some((service) => service.isActive && service.nameEn)).slice(0, 6);

  return <main lang="en" dir="ltr" className="overflow-x-hidden bg-cut-black text-cut-ivory">
    <section className="relative isolate min-h-[760px] overflow-hidden bg-cut-black pt-24 lg:min-h-[820px]">
      <div className="absolute inset-y-0 right-0 hidden w-[58%] lg:block"><img src="/hero.png" alt="A CUT Salon grooming moment" className="h-full w-full object-cover object-right opacity-75" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#050505_0%,rgba(5,5,5,0.48)_45%,rgba(74,0,15,0.16)_100%)]" /></div>
      <div className="absolute -left-48 top-24 h-[36rem] w-[36rem] rounded-full border border-cut-bronze/20" /><div className="absolute right-[19%] top-[19%] hidden h-32 w-32 rotate-45 border border-cut-warm-beige/30 lg:block" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_82%_28%,rgba(74,0,15,0.8),transparent_28%),radial-gradient(circle_at_20%_85%,rgba(74,0,15,0.38),transparent_35%)]" />
      <p aria-hidden className="pointer-events-none absolute -bottom-8 left-1/2 -translate-x-1/2 whitespace-nowrap font-display text-[clamp(5rem,17vw,16rem)] font-bold text-cut-ivory/[0.035]">CUT SALON</p>
      <div className="relative mx-auto grid min-h-[690px] max-w-[1360px] items-center gap-12 px-[clamp(24px,5vw,80px)] pb-24 lg:grid-cols-12"><div className="lg:col-span-6"><Eyebrow>{copy.hero.eyebrow}</Eyebrow><h1 className="mt-7 max-w-3xl font-editorial text-[clamp(4rem,7vw,7.4rem)] font-semibold leading-[0.88] tracking-tight">{copy.hero.title}</h1><p className="mt-8 max-w-xl text-lg leading-8 text-cut-ivory/70">{copy.hero.body}</p><div className="mt-10 flex flex-wrap gap-3"><button onClick={() => document.getElementById("english-barbers")?.scrollIntoView({ behavior: "smooth" })} className="inline-flex min-h-12 items-center gap-2 bg-cut-ivory px-6 font-bold text-cut-black transition hover:bg-cut-warm-beige">Book Now <ArrowRight className="h-4 w-4" /></button><button onClick={() => openBooking(nearestBarber, "nearest")} className="inline-flex min-h-12 items-center gap-2 border border-cut-bronze/55 px-6 font-bold transition hover:bg-cut-burgundy/40">Find the Nearest Slot <Zap className="h-4 w-4 text-cut-warm-beige" /></button></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-sm text-cut-ivory/65"><span>Open daily from 11:00 AM</span><span>Professional barbers</span><span>Clear, organized queue</span></div></div></div>
    </section>

    <section id="english-barbers" className="relative overflow-hidden py-28"><p aria-hidden className="pointer-events-none absolute -right-8 top-6 font-display text-[clamp(6rem,17vw,14rem)] font-bold text-cut-ivory/[0.035]">BARBERS</p><div className="relative mx-auto max-w-[1360px] px-[clamp(24px,5vw,80px)]"><Eyebrow>AVAILABLE TODAY</Eyebrow><div className="mt-5 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><h2 className="font-editorial text-[clamp(3rem,5vw,4.8rem)] font-semibold">Choose your chair.</h2><p className="mt-4 max-w-xl text-lg leading-8 text-cut-ivory/65">Choose your barber or view the nearest available time.</p></div><button onClick={() => openBooking(nearestBarber, "nearest")} className="inline-flex min-h-12 items-center gap-2 border border-cut-bronze/45 px-5 font-bold text-cut-warm-beige hover:bg-cut-burgundy/35">Find nearest slot <ArrowRight className="h-4 w-4" /></button></div>{status === "branch" ? <div className="mt-10 max-w-xl border border-cut-bronze/30 bg-cut-soft-black p-6"><h3 className="text-xl font-bold">Select a branch to see availability</h3><div className="mt-5"><BranchPicker branches={branches} selectedBranchCode={selectedBranch?.branchCode} isLoading={isLoadingBranches} error={branchesError} variant="dark" onSelect={selectBranch} /></div></div> : status === "closed" ? <div className="mt-10 max-w-xl border border-cut-bronze/30 bg-cut-wine-black p-6"><p className="font-bold">Online booking is temporarily unavailable.</p><p className="mt-2 text-sm text-cut-ivory/65">Call 035861483 or 01012126899 for assistance.</p></div> : <div className="mt-10 flex gap-5 overflow-x-auto pb-2">{(barbers.length ? barbers : status === "loading" ? Array.from({ length: 4 }, () => null) : []).map((barber, index) => barber ? <article key={barber.id} className="group flex min-w-[255px] flex-1 flex-col border border-cut-bronze/25 bg-cut-soft-black transition hover:-translate-y-1 hover:border-cut-bronze/60"><img src={barber.photoUrl || fallbackImages[index % fallbackImages.length]} alt={barber.name} className="h-56 w-full object-cover object-top transition duration-500 group-hover:scale-[1.03]" /><div className="flex flex-1 flex-col p-5"><p className="font-editorial text-3xl font-semibold">{barber.name}</p><p className="mt-2 text-sm text-cut-ivory/60">{barber.job || "CUT Salon Barber"}</p><p className="mt-6 text-sm text-cut-warm-beige">Available — view live times</p><button onClick={() => openBooking(displayBarber(barber, index), "specific")} className="mt-auto pt-6 text-left text-sm font-bold text-cut-ivory underline decoration-cut-bronze underline-offset-8">View Times</button></div></article> : <div key={index} className="h-[390px] min-w-[255px] animate-pulse border border-cut-bronze/15 bg-cut-soft-black" />)}</div>}</div></section>

    <section id="services" className="relative overflow-hidden bg-cut-soft-ivory py-28 text-cut-black"><p aria-hidden className="pointer-events-none absolute -left-5 top-5 font-display text-[clamp(6rem,17vw,14rem)] font-bold text-cut-black/[0.035]">SERVICES</p><div className="relative mx-auto max-w-[1360px] px-[clamp(24px,5vw,80px)]"><Eyebrow>THE SERVICE EDIT</Eyebrow><h2 className="mt-5 max-w-3xl font-editorial text-[clamp(3rem,5vw,4.8rem)] font-semibold">Crafted for every detail.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-cut-black/65">Explore services designed around your style, routine and occasion.</p><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{featuredServices.map((category, index) => { const active = category.services.filter((service) => service.isActive && service.nameEn); const first = active[0]; return <article key={category.id} className={`group flex min-h-[300px] flex-col overflow-hidden border border-cut-bronze/35 p-6 ${index === 0 ? "bg-cut-wine-black text-cut-ivory lg:col-span-2" : "bg-cut-ivory"}`}><p className={`text-xs font-bold tracking-[0.22em] ${index === 0 ? "text-cut-warm-beige" : "text-cut-burgundy"}`}>CUT SALON SERVICES</p><h3 className="mt-5 font-editorial text-4xl font-semibold">{category.name || "Grooming"}</h3><p className={`mt-4 max-w-sm text-sm leading-7 ${index === 0 ? "text-cut-ivory/70" : "text-cut-black/60"}`}>{active.length} available service{active.length === 1 ? "" : "s"}{first ? ` · from ${money(Math.min(...active.map((service) => service.price)))}` : ""}</p><a href="/prices" className={`mt-auto inline-flex min-h-11 items-center gap-2 pt-8 text-sm font-bold ${index === 0 ? "text-cut-warm-beige" : "text-cut-burgundy"}`}>Explore Services <ChevronRight className="h-4 w-4" /></a></article>; })}<article className="flex min-h-[300px] flex-col border border-cut-bronze/35 bg-cut-burgundy p-6 text-cut-ivory"><Eyebrow>THE GROOM EDIT</Eyebrow><h3 className="mt-6 font-editorial text-4xl font-semibold">Groom Packages</h3><p className="mt-4 text-sm leading-7 text-cut-ivory/70">Wedding-day grooming experiences designed around the details that matter.</p><a href="/prices#groom-packages" className="mt-auto inline-flex min-h-11 items-center gap-2 pt-8 font-bold text-cut-warm-beige">Explore the edit <ChevronRight className="h-4 w-4" /></a></article></div></div></section>

    <section id="groom" className="relative isolate overflow-hidden bg-[linear-gradient(115deg,#050505,#250007_58%,#050505)] py-28"><p aria-hidden className="pointer-events-none absolute bottom-0 right-5 font-display text-[clamp(7rem,20vw,17rem)] font-bold text-cut-ivory/[0.035]">GROOM</p><div className="relative mx-auto grid max-w-[1360px] gap-12 px-[clamp(24px,5vw,80px)] lg:grid-cols-12"><div className="lg:col-span-7"><Eyebrow>THE GROOM EDIT</Eyebrow><h2 className="mt-6 max-w-3xl font-editorial text-[clamp(3rem,5vw,5.5rem)] font-semibold leading-[0.95]">Prepared for the moment that matters most.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-cut-ivory/70">Complete wedding-day grooming experiences combining haircut, beard preparation, skincare and final styling in one carefully planned session.</p><div className="mt-9 flex flex-wrap gap-3 text-sm text-cut-warm-beige"><span className="border border-cut-bronze/35 px-4 py-3">3 tailored packages</span><span className="border border-cut-bronze/35 px-4 py-3">75–180 minute experiences</span><span className="border border-cut-bronze/35 px-4 py-3">On-location finishing</span></div><div className="mt-10 flex flex-wrap gap-3"><a href="/prices#groom-packages" className="inline-flex min-h-12 items-center bg-cut-ivory px-6 font-bold text-cut-black">Explore Groom Packages</a><a href="/prices#groom-quiz" className="inline-flex min-h-12 items-center border border-cut-bronze/50 px-6 font-bold">Help Me Choose</a></div></div><div className="border border-cut-bronze/25 bg-cut-black/35 p-6 lg:col-span-5"><p className="text-xs font-bold tracking-[0.25em] text-cut-bronze">THE JOURNEY</p><ol className="mt-8 space-y-5">{["Consultation", "Hair", "Beard", "Skin", "Final Styling"].map((step, index) => <li key={step} className="flex items-center gap-4"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-cut-bronze/50 text-xs text-cut-warm-beige">0{index + 1}</span><span className="font-editorial text-2xl">{step}</span></li>)}</ol></div></div></section>

    <section className="relative overflow-hidden py-28"><p aria-hidden className="pointer-events-none absolute left-1/2 top-10 -translate-x-1/2 whitespace-nowrap font-display text-[clamp(4rem,11vw,10rem)] font-bold text-cut-ivory/[0.03]">THE CUT STANDARD</p><div className="relative mx-auto max-w-[1360px] px-[clamp(24px,5vw,80px)]"><Eyebrow>WHY CUT SALON</Eyebrow><h2 className="mt-5 font-editorial text-[clamp(3rem,5vw,4.8rem)] font-semibold">The CUT Standard.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-cut-ivory/65">More than a haircut. A smoother experience from arrival to final styling.</p><div className="mt-12 divide-y divide-cut-bronze/25 border-y border-cut-bronze/25">{copy.benefits.map(([number, title, description, Icon]) => <article key={String(number)} className="grid gap-5 py-7 transition hover:bg-cut-burgundy/15 md:grid-cols-[90px_1fr_1.4fr_40px]"><span className="font-display text-3xl text-cut-bronze">{number}</span><h3 className="font-editorial text-3xl font-semibold">{title}</h3><p className="max-w-xl leading-7 text-cut-ivory/65">{description}</p><Icon className="h-6 w-6 text-cut-warm-beige" /></article>)}</div></div></section>

    <section className="bg-cut-soft-black py-28"><div className="mx-auto max-w-[1360px] px-[clamp(24px,5vw,80px)]"><Eyebrow>HOW BOOKING WORKS</Eyebrow><h2 className="mt-5 font-editorial text-[clamp(3rem,5vw,4.8rem)] font-semibold">Book in three simple steps.</h2><div className="mt-12 grid gap-7 md:grid-cols-3">{copy.steps.map(([number, title, description], index) => <article key={String(number)} className="relative border-t border-cut-bronze/50 pt-7">{index < 2 && <span className="absolute right-0 top-[-1px] hidden h-px w-full translate-x-full bg-cut-bronze/30 md:block" />}<p className="font-display text-3xl text-cut-bronze">{number}</p><h3 className="mt-5 font-editorial text-3xl font-semibold">{title}</h3><p className="mt-4 leading-7 text-cut-ivory/65">{description}</p></article>)}</div><p className="mt-12 border-l-2 border-cut-bronze/60 pl-5 text-sm leading-7 text-cut-ivory/60">Appointments follow the live availability and notice rules for your selected branch. Walk-ins are also welcome through our organized queue.</p></div></section>

    <section id="branches" className="relative overflow-hidden bg-cut-ivory py-28 text-cut-black"><p aria-hidden className="pointer-events-none absolute bottom-0 left-4 font-display text-[clamp(5rem,16vw,14rem)] font-bold text-cut-black/[0.035]">ALEXANDRIA</p><div className="relative mx-auto max-w-[1360px] px-[clamp(24px,5vw,80px)]"><Eyebrow>OUR LOCATIONS</Eyebrow><h2 className="mt-5 font-editorial text-[clamp(3rem,5vw,4.8rem)] font-semibold">Choose Your CUT.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-cut-black/65">Find the branch that fits your day and view its available services and times.</p><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{branches.map((branch) => <article key={branch.branchCode} className="flex min-h-[270px] flex-col border border-cut-bronze/35 bg-cut-soft-ivory p-6"><MapPin className="h-7 w-7 text-cut-burgundy" /><h3 className="mt-8 font-editorial text-3xl font-semibold">{branch.shortName || branch.branchName}</h3><p className="mt-3 text-sm leading-7 text-cut-black/60">{branch.address || "Alexandria, Egypt"}</p><p className="mt-4 text-sm">Open daily from 11:00 AM</p><div className="mt-auto flex flex-wrap gap-3 pt-7"><button onClick={() => selectBranch(branch)} className="min-h-11 border border-cut-burgundy px-4 text-sm font-bold text-cut-burgundy">View Branch</button><button onClick={() => { selectBranch(branch); openBooking(nearestBarber, "nearest"); }} className="min-h-11 bg-cut-black px-4 text-sm font-bold text-cut-ivory">Book at This Branch</button></div></article>)}</div></div></section>

    <section className="relative isolate overflow-hidden bg-cut-burgundy py-28"><p aria-hidden className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 whitespace-nowrap font-display text-[clamp(5rem,15vw,13rem)] font-bold text-cut-ivory/[0.05]">BOOK YOUR CUT</p><div className="relative mx-auto max-w-[1360px] border-y border-cut-bronze/35 px-[clamp(24px,5vw,80px)] py-16"><Eyebrow>READY WHEN YOU ARE</Eyebrow><h2 className="mt-6 max-w-3xl font-editorial text-[clamp(3rem,5vw,5.5rem)] font-semibold">Your next look starts here.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-cut-ivory/70">Choose your service, barber and preferred time in a few simple steps.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => openBooking(nearestBarber, "nearest")} className="inline-flex min-h-12 items-center bg-cut-ivory px-6 font-bold text-cut-black">Book Now</button><a href="/prices" className="inline-flex min-h-12 items-center border border-cut-warm-beige/55 px-6 font-bold">Explore Prices</a></div></div></section>

    <footer className="bg-cut-black py-16"><div className="mx-auto grid max-w-[1360px] gap-10 px-[clamp(24px,5vw,80px)] md:grid-cols-4"><div><p className="font-display text-3xl font-bold tracking-[0.2em]">CUT</p><p className="mt-1 text-xs font-bold tracking-[0.45em] text-cut-bronze">SALON</p><p className="mt-5 max-w-xs text-sm leading-7 text-cut-ivory/60">Refined grooming, designed around detail, confidence and your time.</p></div><div><p className="font-bold text-cut-warm-beige">Explore</p><div className="mt-5 space-y-3 text-sm text-cut-ivory/65"><a href="#services" className="block hover:text-cut-ivory">Services</a><a href="/prices" className="block hover:text-cut-ivory">Prices</a><a href="#groom" className="block hover:text-cut-ivory">Groom</a><a href="#english-barbers" className="block hover:text-cut-ivory">Barbers</a><a href="/client/loyalty" className="block hover:text-cut-ivory">CUT CLUB</a></div></div><div><p className="font-bold text-cut-warm-beige">Branches</p><div className="mt-5 space-y-3 text-sm text-cut-ivory/65">{branches.map((branch) => <button key={branch.branchCode} onClick={() => selectBranch(branch)} className="block text-left hover:text-cut-ivory">{branch.shortName || branch.branchName}</button>)}</div></div><div><p className="font-bold text-cut-warm-beige">Contact</p><div className="mt-5 space-y-3 text-sm text-cut-ivory/65"><a href="tel:035861483" className="block hover:text-cut-ivory">035861483</a><a href="tel:01012126899" className="block hover:text-cut-ivory">01012126899</a><p>Open daily from 11:00 AM</p><p>Online booking subject to live availability.</p></div></div></div><div className="mx-auto mt-12 flex max-w-[1360px] flex-wrap justify-between gap-4 border-t border-cut-bronze/20 px-[clamp(24px,5vw,80px)] pt-6 text-xs text-cut-ivory/45"><span>© 2026 CUT Salon. All rights reserved.</span><span>Privacy Policy · Terms</span></div></footer>

    {selectedBarber && <BookingModal open={Boolean(selectedBarber)} onOpenChange={(open) => { if (!open) { setSelectedBarber(null); setBookingMode(undefined); } }} barber={selectedBarber} initialMode={bookingMode} />}
  </main>;
}
